name: Prueba de Mensaje WhatsApp

on: [push]

jobs:
  test-envio:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar codigo
        uses: actions/checkout@v4

      - name: Simular una tarea exitosa
        run: echo "Hola, probando GitHub Actions"

      - name: Enviar Notificacion a mi WhatsApp
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: 'whatsapp:+14155238886' 
          toPhoneNumber: 'whatsapp:+593995031599'   
          message: |
            🚀 *¡Prueba Exitosa desde GitHub Actions!*
            
            Hola Alex, el flujo de prueba funcionó correctamente con los nuevos parámetros.
            *Repo:* ${{ github.repository }}
            *Commit:* ${{ github.event.head_commit.message }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
